### ISSUE TITLE
No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=audio/* flg=0x40 }

### ISSUE THREAD

**Issue by DeweyReed** [DeweyReed/UltimateMusicPicker#18]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=audio/* flg=0x40 }
  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2290)
  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1951)
  at android.app.Activity.startActivityForResult(Activity.java:4630)
  at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:10)
  at androidx.core.app.ActivityCompat.[finishAffinity | getPermissionCompatDelegate | requestPermissions | requireViewById | shouldShowRequestPermissionRationale | startActivityForResult | startIntentSenderForResult](ActivityCompat.java)
  at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:28)
  at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java)
  at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java)
  at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java)
  at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java)
  at xyz.aprildown.ultimateringtonepicker.UtilsKt.gone(UtilsKt.java:26)
  at xyz.aprildown.ultimateringtonepicker.UtilsKt.isLOrLater(UtilsKt.java:26)
  at xyz.aprildown.ultimateringtonepicker.UtilsKt.launchSaf(UtilsKt.java:26)
  at xyz.aprildown.ultimateringtonepicker.UtilsKt.safeContext(UtilsKt.java:26)
  at xyz.aprildown.ultimateringtonepicker.UtilsKt.startDrawableAnimation(UtilsKt.java:26)
  at xyz.aprildown.ultimateringtonepicker.ui.DeviceRingtoneFragment$1$1.onChanged(DeviceRingtoneFragment.java)
  at xyz.aprildown.ultimateringtonepicker.ui.DeviceRingtoneFragment$1$1.onChanged(DeviceRingtoneFragment.java)
  at androidx.lifecycle.LiveData.considerNotify(LiveData.java:29)
  at androidx.lifecycle.LiveData.getValue(LiveData.java:29)
  at androidx.lifecycle.LiveData.removeObserver(LiveData.java:29)
  at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:44)
  at androidx.lifecycle.LiveData.hasActiveObservers(LiveData.java:44)
  at androidx.lifecycle.LiveData.setValue(LiveData.java:44)
  at androidx.lifecycle.LiveData.setValue(LiveData.java)
  at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java)
  at androidx.lifecycle.LiveData$1.run(LiveData.java:18)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:220)
  at android.app.ActivityThread.main(ActivityThread.java:7420)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
```

Device: NX609J, Android 9

It seems some devices have removed SAF.

**Comment by DeweyReed** [comment]
I added a try-catch in 294b3b23, but the library requires a fallback solution.

**Comment by methuselahin** [comment]
@DeweyReed do you have this device? And android 9 on this device is Chinese ROM. The international ROM was stuck at oreo 8.1. Or u are using a GSI?

**Comment by DeweyReed** [comment]
@methuselahin I don't have the device. The stack trace is from a crash report service.

**Comment by methuselahin** [comment]
@DeweyReed oh okay. sad no one has got this device around. Matter of fact we are stuck with android 8.1 on international version. There is this 9.0 chinese ROM. nothing international version is dropped on 8.1 by nubia only. Do you have any knowledge abt gsi working?

**Comment by DeweyReed** [comment]
@methuselahin I'm sorry, but I know nothing about GSI.

I can barely find any information about the device on the web. It looks like a modified gaming phone.

**Comment by methuselahin** [comment]
u can ask me anything abt the phone. it was nubia red magic. nx609j.

**Comment by DeweyReed** [comment]
@methuselahin Thanks for your kindness. The problem isn't unique to NX609J. After a little investigation, I find out that the missing of SAF appears on many other devices.

**Comment by methuselahin** [comment]
@DeweyReed  oh okay. Glad you cud fine the issue on other devices also. 🙂

**Comment by methuselahin** [comment]
@DeweyReed you are android developer! Can you have a look at these logs [https://github.com/phhusson/treble_experimentations/issues/491](url) Anything you see here, why there is no sound from speaker'?

**Comment by DeweyReed** [comment]
@methuselahin I'm sorry, but I'm not familiar with Android framework/system development. There is nothing I can do.

**Comment by methuselahin** [comment]
@DeweyReed oh its okay :). Thanks for replying

**Comment by DeweyReed** [comment]
I'm closing the issue because

- The code to launch SAF is from [AOSP](https://android.googlesource.com/platform/packages/apps/DeskClock/+/refs/heads/master/src/com/android/deskclock/ringtone/RingtonePickerActivity.kt#422), and there isn't much we can do on our part.
- [Signal-Android](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/mms/AttachmentManager.java#L458) also has a similar fallback solution.

My suggestion is to check SAF availability before relying on it.

**Comment by ayush19283** [comment]
@DeweyReed did you get any solution for this (device that does not support SAF)

**Comment by DeweyReed** [comment]
@ayush19283 This library provides a solution that uses the `READ_MEDIA_AUDIO` permission and shows all audio files without opening other apps.

**Comment by ayush19283** [comment]
@DeweyReed what about other files like enc files html files? can i access them through any method? 
I have tried all solutions by installing documentsui file browsers and all nothing worked.

**Comment by DeweyReed** [comment]
@ayush19283 They are not audio files, so this library does not support picking them.

If you'd like to pick them in your app without using SAF, I think you'll have to [manage all files on a device](https://developer.android.com/training/data-storage/manage-all-files), which probably causes some policy issues in Google Play. My approach would be to show a message to the user explaining why the feature is unavailable, considering the system isn't complete.
