### ISSUE TITLE
Unknown URL: content://media/external/file/-1

### ISSUE THREAD

**Issue by DeweyReed** [DeweyReed/UltimateMusicPicker#23]
```
Fatal Exception: java.lang.IllegalStateException: Unknown URL: content://media/external/file/-1
       at android.os.Parcel.readException(Parcel.java:1692)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
       at android.content.ContentResolver.query(ContentResolver.java:534)
       at android.content.ContentResolver.query(ContentResolver.java:475)
       at xyz.aprildown.ultimateringtonepicker.data.folder.RingtoneFolderRetrieverPreQ.getRingtoneFolders()
       at xyz.aprildown.ultimateringtonepicker.RingtonePickerViewModel$categories$2$$special$$inlined$also$lambda$1.xyz.aprildown.ultimateringtonepicker.data.folder.RingtoneFolderRetrieverCompat.getRingtoneFolders(:7)
                                                                                                                    xyz.aprildown.ultimateringtonepicker.data.DeviceRingtoneModel.getFolders
                                                                                                                    xyz.aprildown.ultimateringtonepicker.data.DeviceRingtoneModel.getCategories
                                                                                                                    invokeSuspend
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(:2)
       at kotlinx.coroutines.DispatchedTask.run()
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely()
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(:7)
                                                                  runWorker
                                                                  run

```

**Comment by adrcotfas** [comment]
Hey @DeweyReed, in what situation does this bug appear?

**Comment by DeweyReed** [comment]
@adrcotfas I have no idea. I'll try-catch the related code in the next release.
